//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryAudit
    {
        public int AuditId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> DeletedSalary { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
