//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_library
    {
        public int id { get; set; }
        public Nullable<int> Studentid { get; set; }
        public string Bookname { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<System.DateTime> Returndate { get; set; }
    
        public virtual t_user t_user { get; set; }
    }
}
