//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MARKSHEET
    {
        public int MarksheetId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<decimal> marks { get; set; }
    
        public virtual T_Student T_Student { get; set; }
        public virtual T_SUBJECT T_SUBJECT { get; set; }
    }
}
