//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Salary
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string MonthName { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual t_Employee t_Employee { get; set; }
    }
}
