//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Student()
        {
            this.T_MARKSHEET = new HashSet<T_MARKSHEET>();
        }
    
        public int id { get; set; }
        public string sname { get; set; }
        public string SemNo { get; set; }
        public string Mobile { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MARKSHEET> T_MARKSHEET { get; set; }
    }
}
